openapi: 3.0.0

info:
  title: Taller de Coches - Subsistema de Env铆o de Notificaciones
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /notificaciones/correo:
    post:
      summary: Env铆o de notificaci贸n de cambio de estado del trabajo por correo
      description: Env铆a una notificaci贸n por correo al cliente cuando cambia el estado de un trabajo
      tags:
        - "Notificaciones "
      requestBody:
        $ref: '#/components/requestBodies/NotificacionRB'
      responses:
        '200':
          $ref: '#/components/responses/NotificacionResponse'
        '400':
          $ref: '#/components/responses/Response400'
  /notificaciones/telefono:
    post:
      summary: Env铆o de notificaci贸n de cambio de estado del trabajo por tel茅fono
      description: Env铆a una notificaci贸n por tel茅fono al cliente cuando cambia el estado de un trabajo
      tags:
        - "Notificaciones "
      requestBody:
        $ref: '#/components/requestBodies/NotificacionRB'
      responses:
        '200':
          $ref: '#/components/responses/NotificacionResponse'
        '400':
          $ref: '#/components/responses/Response400'
  /notificaciones/masivas:
    post:
      summary: Env铆o de notificaci贸n masiva
      description: Env铆a una notificaci贸n a todos los clientes con trabajos pendientes
      tags:
        - "Notificaciones"
      requestBody:
        $ref: '#/components/requestBodies/NotificacionMasivaRB'
      responses:
        '200':
          $ref: '#/components/responses/NotificacionMasivaResponse'
        '400':
          $ref: '#/components/responses/Response400'
  /notificaciones/{idNotificacion}:
    get:
      summary: Obtener una notificaci贸n
      description: Obtiene una notificaci贸n mediante su id, as铆 como los enlaces a los recursos relacionados
      tags:
        - "Notificaciones "
      parameters:
        - name: idNotificacion
          in: path
          required: true
          description: Identificador 煤nico de la notificaci贸n
          schema:
            type: string
      responses:
        '200':
          description: Notificaci贸n obtenida correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notificacion'
        '400':
          $ref: '#/components/responses/Response400'
        '404':
          $ref: '#/components/responses/Response404'
  /notificaciones/{idTrabajo}:
    get:
      summary: Obtener notificaciones de un trabajo
      description: Obtiene todas las notificaciones de un trabajo, as铆 como los enlaces a los recursos relacionados
      tags:
        - "Notificaciones "
      parameters:
        - name: idTrabajo
          in: path
          required: true
          description: Identificador 煤nico del trabajo
          schema:
            type: string
      responses:
        '200':
          description: Notificaciones del trabajo obtenidas correctamente
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Notificacion'
        '400':
          $ref: '#/components/responses/Response400'
        '404':
          $ref: '#/components/responses/Response404'
  /notificaciones/{idCliente}:
    get:
      summary: Obtener notificaciones de un cliente
      description: Obtiene todas las notificaciones de un cliente, as铆 como los enlaces a los recursos relacionados
      tags:
        - "Notificaciones "
      parameters:
        - name: idCliente
          in: path
          required: true
          description: Identificador 煤nico del cliente
          schema:
            type: string
      responses:
        '200':
          description: Notificaciones del cliente obtenidas correctamente
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Notificacion'
        '400':
          $ref: '#/components/responses/Response400'
        '404':
          $ref: '#/components/responses/Response404'
    patch:
      summary: Actualizar la suscripci贸n a notificaciones
      description: Actualiza la suscripci贸n a notificaciones de un cliente
      tags:
        - "Notificaciones "
      requestBody:
        $ref: '#/components/requestBodies/SuscripcionNotificacionesRB'
      responses:
        '200':
          description: Suscripci贸n actualizada correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cliente'
        '400':
          $ref: '#/components/responses/Response400'
        '404':
          $ref: '#/components/responses/Response404'

components:
  schemas:
    Trabajo:
      type: object
      properties:
        idTrabajo:
          type: string
        estado:
          type: string
        descripcion:
          type: string
        fechaInicio:
          type: string
          format: date-time
        fechaFin:
          type: string
          format: date-time
        vehiculo:
          $ref: '#/components/schemas/Vehiculo'
        notificaciones:
          type: array
          items:
            $ref: '#/components/schemas/Notificacion'
      required:
          - idTrabajo
          - estado
          - descripcion
          - fechaInicio
          - vehiculo
    Notificacion:
      type: object
      properties:
        idNotificacion:
          type: string
        idTrabajo:
          type: string
        mensaje:
          type: string
        fechaEnvio:
          type: string
          format: date-time
        estado:
          type: string
        enlaces:
          type: array
          items:
            type: integer
      required:
        - idNotificacion
        - idTrabajo
        - mensaje
        - fechaEnvio
        - estado
      example:
        idNotificacion: "ij2409234h2"
        idTrabajo: "87da6d898d"
        mensaje: "El trabajo ha sido realizado"
        fechaEnvio: "2023-04-10T17:51:00Z"
        estado: "enviada"
        enlaces:
          - rel: "self"
            href: "https://ejemplo.com/api/v1/notificaciones/ij2409234h2"
          - rel: "trabajo"
            href: "https://ejemplo.com/api/v1/trabajos/87da6d898d"
    Vehiculo:
      type: object
      properties:
        vin:
          type: string
        marca:
          type: string
        modelo:
          type: string
        year:
          type: integer
        cliente:
          type: integer
      required:
        - vin
        - marca
        - modelo
        - year
        - cliente
      example:
        vin: "1HGCM82633A004352"
        marca: "Mercedes"
        modelo: "Clase A"
        year: 2023
        cliente:
          idCliente: "7y2f5g28974y"
          nombre: "Pepe"
          apellido: "P茅rez"
          correo: "pepeperez@example.com"
          telefono: "689374623"
    Cliente:
      type: object
      properties:
        nombre: 
          type: string
        apellido: 
          type: string
        telefono: 
          type: string
        email: 
          type: string
        direccion: 
          type: string
        recibeNotificaciones:
          type: boolean
      required:
        - nombre
        - apellido
        - telefono
        - email
        - direccion
        - recibeNotificaciones
    NotificacionMasiva:
      type: object
      properties:
        idNotificacion:
          type: string
        mensaje:
          type: string
        fechaEnvio:
          type: string
          format: date-time
  requestBodies:
    NotificacionRB:
      description: Datos de la notificaci贸n a crear
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              idTrabajo:
                type: string
                description: ID del trabajo al que est谩 relacionada la notificaci贸n
              mensaje:
                type: string
                description: Mensaje de la notificaci贸n
            required:
              - idTrabajo
              - mensaje
    NotificacionMasivaRB:
      description: Datos de una notificaci贸n masiva
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              mensaje:
                type: string
                description: Mensaje de la notificaci贸n
              fechaProgramada: 
                type: string
                format: date-time
            required:
              - mensaje
    SuscripcionNotificacionesRB:
      description: Datos de la suscripci贸n a las notificaciones 
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              idCliente:
                type: string
                description: Id del cliente
              suscripcion:
                type: boolean
                description: indica si un usuario est谩 suscrito a las notificaciones
  responses:
    NotificacionResponse:
      description: Notificaci贸n enviada correctamente
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Notificacion'
    NotificacionMasivaResponse:
      description: Notificaci贸n masiva enviada correctamente
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotificacionMasiva'
    Response400:
      description: "Bad Request"
    Response404:
      description: "`NOT FOUND`: resource not found"

    